spring:
  profiles: h1
  application:
    name: discovery
server:
  port: 8761
eureka:
  instance:
    # hostname需要再hosts里映射对应ip
    hostname: h1
  client:
    #配置服务注册中心是否以自己为客户端进行注册(配置false)
    register-with-eureka: true
    #是否取得注册信息(配置false)
    fetch-registry: true
    serviceUrl:
      # defaultXone 不能写iP
      defaultZone: http://h2:8761/eureka/,http://h3:8761/eureka/

---
spring:
  profiles: h2
  application:
    name: discovery
server:
  port: 8761
eureka:
  instance:
    hostname: h2
  client:
    register-with-eureka: true
    #配置服务注册中心是否以自己为客户端进行注册(配置false)
    fetch-registry: true
    #是否取得注册信息(配置false)
    serviceUrl:
      defaultZone: http://h1:8761/eureka/,http://h3:8761/eureka/

---
spring:
  profiles: h3
  application:
    name: discovery
server:
  port: 8761
eureka:
  instance:
    hostname: h3
  client:
    register-with-eureka: true
    #配置服务注册中心是否以自己为客户端进行注册(配置false)
    fetch-registry: true
    #是否取得注册信息(配置false)
    serviceUrl:
      defaultZone: http://h1:8761/eureka/,http://h2:8761/eureka/