spring:
  profiles: d1
  application:
    name: discovery
server:
  port: 8761
eureka:
  instance:
    # hostname需要再hosts里映射对应ip
    hostname: descovery-1
  client:
    #配置服务注册中心是否以自己为客户端进行注册(配置false)
    register-with-eureka: true
    #是否取得注册信息(配置false)
    fetch-registry: true
    serviceUrl:
      # defaultXone 不能写iP
      defaultZone: http://descovery-2:8761/eureka/

---
spring:
  profiles: d2
  application:
    name: discovery
server:
  port: 8761
eureka:
  instance:
    hostname: descovery-2
  client:
    register-with-eureka: true
    #配置服务注册中心是否以自己为客户端进行注册(配置false)
    fetch-registry: true
    #是否取得注册信息(配置false)
    serviceUrl:
      defaultZone: http://descovery-1:8761/eureka/